<!DOCTYPE html> 
<html> 
	<head> 
		<meta charset=UTF-8 /> 
		<meta name="description" content="" />
		<meta name="author" content="Protarget Estrategia Promocional" />
		<meta name="keywords"content="" />
		<title><?php echo title();?></title>
		<link rel="stylesheet" href="<?= URL;?>/style/style.css" type="text/css" media="screen" />
	</head>
	<body>
		<div id="wrapper">
				<?php echo $content; ?>
		</div>
	<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
	<!-- Your Javascript Code And links Here -->
	<?php js_print(); ?>
	</body>
</html>